In [3]:
import pandas as pd
읽기=pd.read_csv('./NHIS_OPEN_T20_2008.csv',engine="python")

In [4]:
읽기

,기준년도,가입자 일련번호,진료내역일련번호,성별코드,연령대코드,시도코드,요양개시일자,서식코드,진료과목코드,주상병코드,...,요양일수,입내원일수,심결가산율,심결요양급여비용총액,심결본인부담금,심결보험자부담금,심결씨티총액,심결엠알아이총액,총처방일수,데이터 기준일자
0,2008,436625,1,2,13,26,20081208,3,1,J42,...,1,1,15,8350,2500,5850,0,0,7.0,20151220
1,2008,536663,2,2,10,26,20081224,3,1,J450,...,1,1,15,8420,2500,5920,0,0,6.0,20151220
2,2008,718041,3,2,8,26,20081208,3,1,J041,...,1,1,15,13650,4000,9650,0,0,1.0,20151220
3,2008,435154,4,1,9,26,20081210,3,1,J980,...,1,1,15,43470,13000,30470,0,0,3.0,20151220
4,2008,435154,5,1,9,26,20081226,3,1,J450,...,1,1,15,8360,2500,5860,0,0,3.0,20151220
5,2008,435154,6,1,9,26,20081229,3,1,J450,...,1,1,15,8360,2500,5860,0,0,3.0,20151220
6,2008,441547,7,1,9,26,20081201,3,1,J450,...,1,1,15,11710,3500,8210,0,0,5.0,20151220
7,2008,441547,8,1,9,26,20081212,3,1,K319,...,1,1,15,8380,2500,5880,0,0,6.0,20151220
8,2008,432029,9,1,5,26,20081230,3,1,K297,...,1,1,15,11680,3500,8180,0,0,3.0,20151220
9,2008,87953,10,2,10,47,20081202,3,10,N959,...,1,1,15,8770,2600,6170,0,0,14.0,20151220
10,2008,535215,11,2,12,47,20081202,3,10,N768,...,1,1,15,8770,2600,6170,0,0,1.0,20151220
11,2008,535215,12,2,12,47,20081219,3,10,N768,...,1,1,15,8770,2600,6170,0,0,1.0,20151220
12,2008,198605,13,2,6,47,20081203,3,10,N768,...,1,1,15,10600,3100,7500,0,0,0.0,20151220
13,2008,794790,14,2,6,47,20081208,3,10,N735,...,1,1,15,16370,4900,11470,0,0,7.0,20151220
14,2008,794790,15,2,6,47,20081220,3,10,N735,...,1,1,15,10140,3000,7140,0,0,5.0,20151220
15,2008,802569,16,2,7,47,20081215,3,10,N768,...,1,1,15,8350,2500,5850,0,0,1.0,20151220
16,2008,783218,17,2,10,47,20081219,3,10,N945,...,1,1,15,8350,2500,5850,0,0,3.0,20151220
17,2008,199314,18,2,9,47,20081226,3,10,N735,...,1,1,15,12100,3600,8500,0,0,3.0,20151220
18,2008,199314,19,2,9,47,20081231,3,10,N735,...,1,1,15,8770,2600,6170,0,0,3.0,20151220
19,2008,970003,20,2,5,47,20081230,3,10,N735,...,1,1,15,13470,4000,9470,0,0,3.0,20151220
20,2008,193311,21,2,12,46,20081210,3,1,K291,...,1,1,15,11680,3500,8180,0,0,5.0,20151220
21,2008,193311,22,2,12,46,20081215,3,1,K291,...,1,1,15,8350,2500,5850,0,0,5.0,20151220
22,2008,193311,23,2,12,46,20081222,3,1,K293,...,1,1,15,8350,2500,5850,0,0,5.0,20151220
23,2008,820110,24,1,13,46,20081215,3,1,J00,...,1,1,15,8350,2500,5850,0,0,3.0,20151220
24,2008,459228,25,1,4,46,20081208,3,5,M760,...,1,1,15,15400,4600,10800,0,0,3.0,20151220
25,2008,453492,26,1,11,46,20081227,3,1,J00,...,1,1,15,11690,3500,8190,0,0,3.0,20151220
26,2008,193282,27,2,15,46,20081225,3,1,I10,...,1,1,15,11690,1500,10190,0,0,15.0,20151220
27,2008,225226,28,2,3,46,20081213,3,1,J041,...,1,1,15,8350,2500,5850,0,0,3.0,20151220
28,2008,225226,29,2,3,46,20081216,3,1,J041,...,1,1,15,8350,2500,5850,0,0,3.0,20151220
29,2008,835520,30,2,15,29,20081208,3,5,M170,...,1,1,15,13540,1500,12040,0,0,0.0,20151220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048545,2008,561837,1048546,1,16,41,20081223,3,12,H191,...,1,1,15,14630,1500,13130,0,0,1.0,20151220
1048546,2008,383863,1048547,2,15,41,20081216,3,12,H401,...,1,1,15,16480,4900,11580,0,0,40.0,20151220
1048547,2008,956994,1048548,1,15,41,20081211,3,12,H401,...,1,1,15,16480,4900,11580,0,0,1.0,20151220
1048548,2008,745019,1048549,2,15,41,20081202,3,12,H048,...,1,1,15,13370,1500,11870,0,0,1.0,20151220
1048549,2008,380612,1048550,2,15,41,20081224,3,12,H048,...,1,1,15,13370,1500,11870,0,0,1.0,20151220
1048550,2008,229598,1048551,2,14,41,20081203,3,12,Z961,...,1,1,15,11300,1500,9800,0,0,1.0,20151220
1048551,2008,229598,1048552,2,14,41,20081222,3,12,Z961,...,1,1,15,18790,5600,13190,0,0,0.0,20151220
1048552,2008,895415,1048553,2,13,41,20081218,3,12,H151,...,1,1,15,16480,4900,11580,0,0,5.0,20151220
1048553,2008,916414,1048554,2,12,41,20081216,3,12,H409,...,1,1,15,27290,8100,19190,0,0,0.0,20151220
1048554,2008,368643,1048555,2,12,41,20081201,3,12,H048,...,1,1,15,10040,3000,7040,0,0,1.0,20151220
1048555,2008,477524,1048556,2,12,41,20081230,3,12,H048,...,1,1,15,13370,4000,9370,0,0,1.0,20151220
1048556,2008,265369,1048557,2,10,41,20081210,3,12,H105,...,1,1,15,13370,4000,9370,0,0,2.0,20151220
1048557,2008,864406,1048558,2,6,44,20081210,3,12,H169,...,1,1,15,10040,3000,7040,0,0,1.0,20151220
1048558,2008,251301,1048559,2,6,41,20081229,3,12,H169,...,1,1,15,13370,4000,9370,0,0,1.0,20151220
1048559,2008,297161,1048560,1,6,11,20081208,3,12,H000,...,1,1,15,13370,4000,9370,0,0,2.0,20151220
1048560,2008,619159,1048561,2,5,41,20081216,3,12,H521,...,1,1,15,20850,6200,14650,0,0,0.0,20151220
1048561,2008,885517,1048562,2,4,41,20081215,3,12,H521,...,1,1,15,20850,6200,14650,0,0,0.0,20151220
1048562,2008,641393,1048563,1,4,41,20081202,3,12,H000,...,1,1,15,10040,3000,7040,0,0,2.0,20151220
1048563,2008,392452,1048564,1,3,41,20081215,3,12,H001,...,1,1,15,10040,3000,7040,0,0,2.0,20151220
1048564,2008,115068,1048565,2,3,41,20081218,3,12,H105,...,1,1,15,10040,3000,7040,0,0,1.0,20151220
1048565,2008,720544,1048566,2,5,11,20081208,3,14,L239,...,1,1,15,11680,3500,8180,0,0,3.0,20151220
1048566,2008,588014,1048567,1,11,11,20081208,3,14,B07,...,1,1,15,32800,9800,23000,0,0,0.0,20151220
1048567,2008,633251,1048568,1,12,11,20081210,3,14,L210,...,1,1,15,13140,3900,9240,0,0,5.0,20151220
1048568,2008,297316,1048569,1,13,11,20081212,3,14,B001,...,1,1,15,13280,3900,9380,0,0,5.0,20151220
1048569,2008,593732,1048570,1,9,11,20081213,3,14,B029,...,1,1,15,16510,4900,11610,0,0,2.0,20151220
1048570,2008,41876,1048571,2,9,41,20081216,3,14,L239,...,1,1,15,13150,3900,9250,0,0,7.0,20151220
1048571,2008,667436,1048572,2,4,11,20081216,3,14,L239,...,1,1,15,13140,3900,9240,0,0,3.0,20151220
1048572,2008,43003,1048573,2,2,11,20081222,3,14,T140,...,1,1,15,15660,3200,12460,0,0,2.0,20151220
1048573,2008,297593,1048574,2,11,11,20081224,3,14,L239,...,1,1,15,13380,4000,9380,0,0,3.0,20151220
1048574,2008,649939,1048575,2,7,28,20081224,3,14,L300,...,1,1,15,11680,3500,8180,0,0,1.0,20151220

In [5]:
읽기.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
기준년도          1048575 non-null int64
가입자 일련번호      1048575 non-null int64
진료내역일련번호      1048575 non-null int64
성별코드          1048575 non-null int64
연령대코드         1048575 non-null int64
시도코드          1048575 non-null int64
요양개시일자        1048575 non-null int64
서식코드          1048575 non-null int64
진료과목코드        1048575 non-null int64
주상병코드         1048575 non-null object
부상병코드         687452 non-null object
요양일수          1048575 non-null int64
입내원일수         1048575 non-null int64
심결가산율         1048575 non-null int64
심결요양급여비용총액    1048575 non-null int64
심결본인부담금       1048575 non-null int64
심결보험자부담금      1048575 non-null int64
심결씨티총액        1048575 non-null int64
심결엠알아이총액      1048575 non-null int64
총처방일수         1048572 non-null float64
데이터 기준일자      1048575 non-null int64
dtypes: float64(1), int64(18), object(2)
memory usage: 168.0+ MB

In [6]:
읽기.describe()

,기준년도,가입자 일련번호,진료내역일련번호,성별코드,연령대코드,시도코드,요양개시일자,서식코드,진료과목코드,요양일수,입내원일수,심결가산율,심결요양급여비용총액,심결본인부담금,심결보험자부담금,심결씨티총액,심결엠알아이총액,총처방일수,데이터 기준일자
count,1048575.0,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1048575.0,1048575.0,1.048572e+06,1048575.0
mean,2008.0,5.191164e+05,5.242880e+05,1.572918e+00,8.834989e+00,3.319900e+01,2.008088e+07,3.030715e+00,7.639192e+00,1.116340e+00,1.502944e+00,1.520146e+01,3.832328e+04,8.816552e+03,2.947168e+04,0.0,0.0,6.047450e+00,20151220.0
std,0.0,2.915483e+05,3.026977e+05,4.946546e-01,4.911592e+00,1.240923e+01,3.865650e+02,5.174992e-01,5.936847e+00,1.389096e+00,3.713358e+00,3.352027e+00,2.753621e+05,5.032108e+04,2.292218e+05,0.0,0.0,1.215839e+01,0.0
min,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.100000e+01,2.008010e+07,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,20151220.0
25%,2008.0,2.649740e+05,2.621445e+05,1.000000e+00,4.000000e+00,2.600000e+01,2.008052e+07,3.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.500000e+01,9.640000e+03,2.200000e+03,6.960000e+03,0.0,0.0,1.000000e+00,20151220.0
50%,2008.0,5.221270e+05,5.242880e+05,2.000000e+00,1.000000e+01,3.100000e+01,2.008111e+07,3.000000e+00,9.000000e+00,1.000000e+00,1.000000e+00,1.500000e+01,1.168000e+04,3.000000e+03,8.280000e+03,0.0,0.0,3.000000e+00,20151220.0
75%,2008.0,7.769710e+05,7.864315e+05,2.000000e+00,1.300000e+01,4.400000e+01,2.008122e+07,3.000000e+00,1.300000e+01,1.000000e+00,1.000000e+00,1.500000e+01,1.413000e+04,4.000000e+03,1.057000e+04,0.0,0.0,4.000000e+00,20151220.0
max,2008.0,1.008627e+06,1.048575e+06,2.000000e+00,1.800000e+01,4.900000e+01,2.008123e+07,8.000000e+00,5.500000e+01,3.660000e+02,3.660000e+02,3.000000e+01,5.424395e+07,1.061544e+07,4.867107e+07,0.0,0.0,9.990000e+02,20151220.0

In [7]:
읽기.head(3)

,기준년도,가입자 일련번호,진료내역일련번호,성별코드,연령대코드,시도코드,요양개시일자,서식코드,진료과목코드,주상병코드,...,요양일수,입내원일수,심결가산율,심결요양급여비용총액,심결본인부담금,심결보험자부담금,심결씨티총액,심결엠알아이총액,총처방일수,데이터 기준일자
0,2008,436625,1,2,13,26,20081208,3,1,J42,...,1,1,15,8350,2500,5850,0,0,7.0,20151220
1,2008,536663,2,2,10,26,20081224,3,1,J450,...,1,1,15,8420,2500,5920,0,0,6.0,20151220
2,2008,718041,3,2,8,26,20081208,3,1,J041,...,1,1,15,13650,4000,9650,0,0,1.0,20151220